<?php
/**
 * @file
 * the public api for the theme-component-manager
 */


/**
 * Helper method to convert an object to an array
 */
function _object_to_array($obj) {
  if (is_object($obj)) {
    $obj = (array) $obj;
  }
  if (is_array($obj)) {
    $new = array();
    foreach ($obj as $key => $val) {
      $new[$key] = _object_to_array($val);
    }
  }
  else {
    $new = $obj;
  }

  return $new;
}

/**
 * Base class for a component.
 */
class ComponentBase extends StdClass {
  protected $name;
  protected $machineName;
  protected $folder;
  protected $scripts = array();
  protected $styles = array();
  protected $template = FALSE;
  protected $fixture = array();
  protected $options = array();

  /**
   * Constructor.
   */
  public function __construct($folder, $data) {
    $this->name = $data->name;
    $this->machineName = drupal_html_class($this->name);
    $this->folder = $folder;

    $this->scripts = isset($data->scripts) ? $data->scripts : array();
    $this->styles = isset($data->styles) ? $data->styles : array();

    if (!empty($data->backend)) {
      $this->template = !empty($data->backend->template) ? $data->backend->template : FALSE;
      if (!empty($data->backend->arguments)) {
        drupal_set_message(t('Component %component uses old format, split arguments into fixture and options!', array(
          '%component' => $this->name)), 'error');
      }
      foreach (array('fixture', 'options') as $key) {
        if (!empty($data->backend->{$key})) {
          $this->{$key} = _object_to_array($data->backend->{$key});
        }
      }
    }
  }

  /**
   * Get the name of the component.
   */
  public function getName() {
    return $this->name;
  }

  /**
   * Get the machine-name of the component.
   */
  public function getMachineName($with_underscores = FALSE) {
    return $with_underscores ? str_replace('-', '_', $this->machineName) : $this->machineName;
  }

  /**
   * Attach component assets to page.
   */
  public function attachAssets() {
    $mapping = array('drupal_add_js' => $this->scripts, 'drupal_add_css' => $this->styles);
    foreach ($mapping as $func_name => $data) {
      foreach ($data as $script_name) {
        $func_name($this->folder . DIRECTORY_SEPARATOR . $script_name);
      }
    }
  }

  /**
   * Get arguments for this component.
   */
  public function getOptions($options = array()) {
    return drupal_array_merge_deep($this->options, $options);
  }

  /**
   * Get the fixture-data.
   */
  public function getData($data = NULL) {
    return is_null($data) ? $this->fixture : $data;
  }


  public function getTemplate() {
    $pos = strpos($this->template, '.');
    return substr($this->template, 0, $pos);
  }

  public function hasTemplate() {
    return !empty($this->template);
  }

  public function getFolder() {
    return $this->folder;
  }
}


/**
 * Implementation of hook_theme().
 */
function tcm_register_theme_functions($existing, $type, $theme, $path) {

  $components = tcm_get_components();
  $result = array();
  if (!$components) {
    return array();
  }

  foreach ($components as $component) {
    if ($component->hasTemplate()) {
      $result['component_' . $component->getMachineName(TRUE)] = array(
        'variables' => array(
          'component' => NULL,
          'data' => NULL,
          'options' => array(),
        ),
        'path' => $component->getFolder(),
        'template' => $component->getTemplate(),
      );
    }
  }

  return $result;
}

/**
 * Implements hook_theme_registry_alter().
 *
 * Add the preprocess here to keep defaults.
 */
function tcm_theme_registry_alter(&$theme_registry) {
  foreach ($theme_registry as $name => $item) {
    if (substr($name, 0, 10) == 'component_') {
      array_unshift($theme_registry[$name]['preprocess functions'], 'tcm_preprocess_component');
    }
  }
}

/**
 * Find all components and register them.
 */
function _tcm_register_components(&$components, $dir, $recursive) {

  if (!is_dir($dir)) {
    return array();
  }

  if ($handle = opendir($dir)) {
    while (FALSE !== ($file = readdir($handle))) {
      if ($file == '.' || $file == '..') {
        continue;
      }
      $file = $dir . DIRECTORY_SEPARATOR . $file;

      if (is_dir($file)) {
        if ($component = tcm_read_component($file)) {
          // dsm($file, 'found');
          $components[$component->getMachineName()] = $component;
        }
        else {
          if ($recursive) {
            _tcm_register_components($components, $file, $recursive);
          }
          else {
            // dsm("Could not read component from " . $file);
          }
        }
      }
    }
    closedir($handle);
  }
}



function tcm_register_components($path_to_theme) {
  static $components = NULL;
  if (!is_null($components)) {
    return $components;
  }
  $cache_id = 'tcm:components:' . $path_to_theme;
  if (!variable_get('devel_rebuild_theme_registry', FALSE) && $data = cache_get($cache_id)) {
    $components = $data->data;
    // dsm("get from cache");
  }
  else {
    $components = array();
    _tcm_register_components($components, $path_to_theme . '/components', TRUE);
    _tcm_register_components($components, $path_to_theme . '/components_local', FALSE);
    cache_set($cache_id, $components);
    // dsm("get from file-system");
  }

  return $components;
}


/**
 * Get all registered components.
 */
function tcm_get_components($path_to_theme = NULL) {
  return tcm_register_components(isset($path_to_theme) ? $path_to_theme : path_to_theme());
}


/**
 * Read a component.
 */
function tcm_read_component($directory_path) {
  $filename = $directory_path . '/component.json';
  if (!file_exists($filename)) {
    return FALSE;
  }
  $content = file_get_contents($filename);
  $data = json_decode($content);
  if (!empty($data) && is_object($data)) {
    $component = new ComponentBase($directory_path, $data);
    return $component;
  }
  else {
    drupal_set_message(t('Can\t decode component.json at %path', array('%path' => $directory_path)), 'error');
  }
  return FALSE;
}


/**
 * Return a themed component.
 */
function component($component_name, $data = NULL, $options = array()) {
  $components = tcm_get_components();
  if (!isset($components[$component_name])) {
    drupal_set_message(t('Component not found %c', array('%c' => $component_name)));
    $msg = t('missing component %component', array(
      '%component' => $component_name)
    );
    return '<div class="missingComponent">' . $msg . '</div>';
  }

  $component = $components[$component_name];
  if (variable_get('tcm_attach_assets', FALSE)) {
    $component->attachAssets();
  }

  $theme_func = 'component_' . str_replace('-', '_', $component_name);
  return theme($theme_func, array(
    'component' => $component,
    'options' => $options,
    'data' => $data
  ));
}

/**
 * Get all external fixtures.
 */
function _tcm_get_external_fixture_functions() {
  static $cache = NULL;
  if (is_null($cache)) {
    $cache = array(
      'lorem_ipsum' => 'tcm_fixture_lorem_ipsum',
      'lorem_ipsum_html' => 'tcm_fixture_lorem_ipsum_html',
      'image' => 'tcm_fixture_image',
    );
    drupal_alter('tcm_fixture_functions', $cache);
  }

  return $cache;
}


/**
 * Implementation of hook_preprocess_tcm().
 */
function tcm_preprocess_component(&$variables) {
  $fixture_functions = _tcm_get_external_fixture_functions();
  $component = $variables['component'];
  $options = $component->getOptions($variables['options']);
  $data = $component->getData($variables['data']);

  $variables = drupal_array_merge_deep($variables, $options);
  $variables = drupal_array_merge_deep($variables, $data);

  array_walk_recursive($variables,
    function(&$elem) use($fixture_functions) {
      if (is_string($elem) && (strlen($elem) > 0) && ($elem[0] == '@')) {
        $pos_1 = strpos($elem, '(');
        $pos_2 = strpos($elem, ')');
        if (($pos_1 !== FALSE) && ($pos_2 !== FALSE)) {
          $func_name = substr($elem, 1, $pos_1 - 1);
          $params = substr($elem, $pos_1 + 1, $pos_2 - $pos_1 - 1);
          module_load_include('fixturefunctions.inc', 'tcm');
          $func_args = array();
          if (!empty($params)) {
            $func_args = array_map('trim', explode(',', $params));
          }
          if (isset($fixture_functions[$func_name])) {
            $func_name = $fixture_functions[$func_name];
          }
          if (function_exists($func_name)) {
            $elem = call_user_func_array($func_name, $func_args);
          }
          else {
            drupal_set_message(t('Could not find fixture-function %function!', array(
              '%function' => $func_name
            )), 'error');
          }
        }
      }
    }
  );
}

/**
 * Implements hook_menu().
 */
function tcm_menu() {
  return array(
    'admin/components' => array(
      'title' => 'Components',
      'page callback' => 'tcm_page',
      'access arguments' => array('show tcm components'),
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}


/**
 * Implements hook_permission().
 */
function tcm_permission() {
 return array(
    'show tcm components' => array(
      'title' => t('ow TCM components'),
      'description' => t('Show all TCM components.'),
    ),
  );
}

/**
 * Implements hook_admin_paths().
 */
function tcm_admin_paths() {
  $paths = array(
    'admin/components' => FALSE,
    'admin/components/*' => FALSE,
  );
  return $paths;
}

function tcm_page($component_name = FALSE) {
  if ($component_name) {
    return component($component_name);
  }
  $components = tcm_get_components();
  dsm($components);
  $page = array();
  foreach ($components as $component) {
    if (!$component->hasTemplate()) {
      continue;
    }
    $page[] = array(
      array(
        '#prefix' => '<h2>',
        '#suffix' => '</h2>',
        '#markup' => l($component->getName(), 'admin/components/' . $component->getMachineName()),
      ),
      array(
        '#markup' => component($component->getMachineName()),
      )
    );
  };
  return $page;
}
